// Generated by CoffeeScript 1.6.1

/**
 * @author cat.
 * @create 2013-04-08
*/


(function() {
  var Util,
    __slice = [].slice;

  Util = (function() {

    function Util() {}

    /**
    	 * 时间方法
    	 * @param {String} [Y:年 m 月 d 日 H 小时 i 分钟 s 秒钟]
    	 * @param {Number} [时间戳]
    	 * @param {Boolean} 如果最后一个参数是true时就返回时间戳
    */


    Util.prototype.date = function() {
      var args, datetime, flag, i, str, str2fns, time, val, _i, _len;
      args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
      flag = false;
      str = 'Y-m-d H:i:s';
      time = new Date();
      str2fns = [['Y', 'getFullYear'], ['m', 'getMonth'], ['d', 'getDate'], ['H', 'getHours'], ['i', 'getMinutes'], ['s', 'getSeconds']];
      if (typeof args[args.length - 1] === 'boolean') {
        flag = args.pop();
      }
      if (args.length > 1) {
        datetime = args.pop();
        time = new Date(datetime);
      }
      if (args[0]) {
        str = args[0];
      }
      for (i = _i = 0, _len = str2fns.length; _i < _len; i = ++_i) {
        val = str2fns[i];
        if (~str.indexOf(str2fns[i][0])) {
          str = str.replace(str2fns[i][0], function(fn) {
            var t;
            t = time[str2fns[i][1]]();
            if (fn === 'm') {
              t++;
            }
            if ((Math.floor(t / 10)) === 0) {
              t = '0' + t;
            }
            return t;
          });
        }
      }
      if (flag) {
        str = new Date(str).getTime();
      }
      return str;
    };

    return Util;

  })();

  module.exports = new Util();

}).call(this);
